services:
  php3:
    image: php:8.3-fpm
    build: .
    container_name: php3
    volumes:
      - ./customers-microservice:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9003:9000"
    depends_on:
      - mariadb3

  mariadb3:
    image: mariadb:latest
    container_name: mariadb3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3309:3306" # Le port local est maintenant 3309
    volumes:
      - db_data:/var/lib/mysql

  nginx3:
    image: nginx:latest
    container_name: nginx3
    ports:
      - "8084:80"
    volumes:
      - ./customers-microservice:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php3
      
  phpmyadmin3:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin3
    environment:
      PMA_HOST: mariadb # Nom du conteneur MariaDB
      PMA_PORT: 3306    # Port interne utilisé par phpMyAdmin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8085:80" # Accès à phpMyAdmin via le port 8085
    depends_on:
      - mariadb3
volumes:
  db_data:
