services:
  php3:
    image: php:8.3-fpm
    build: .
    container_name: php3
    volumes:
      - ./customers-microservice:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9003:9000"
    depends_on:
      - mariadb3
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      
  mariadb3:
    image: mariadb:latest
    container_name: mariadb3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx3:
    image: nginx:latest
    container_name: nginx3
    ports:
      - "8084:80"
    volumes:
      - ./customers-microservice:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php3

  phpmyadmin3:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin3
    environment:
      PMA_HOST: mariadb3
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - mariadb3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana_data:
