api_platform:
    title: API Customers
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
                