name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@185.170.214.106 << 'EOF'
            # Clone the repo if it doesn't exist
            if [ ! -d "/var/www/customers-microservice/.git" ]; then
              git clone https://BaptisteLT:${{ secrets.TOKEN_GITHUB_CLONE }}@github.com/BaptisteLT/customers-microservice.git /var/www/customers-microservice
            fi

            cd /var/www/customers-microservice || exit
            ls
            git pull origin main
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
          EOF