name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_CLONE }}
        run: |
          ssh -o StrictHostKeyChecking=no root@185.170.214.106 "bash -s" <<EOF
            if [ ! -d "/var/www/customers-microservice/.git" ]; then
              git clone https://BaptisteLT:${GITHUB_TOKEN}@github.com/BaptisteLT/customers-microservice.git /var/www
            fi

            cd /var/www/customers-microservice || exit
            git pull origin main
            ls
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
