services:
  mariadb:
    image: mariadb:latest
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

steps:
  - uses: actions/checkout@v3

  - name: Set up PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.3'
      extensions: pdo, pdo_mysql
      tools: composer

  - name: Wait for MariaDB to be ready
    run: |
      for i in {1..30}; do
        mysqladmin ping -h 127.0.0.1 -uroot -proot && break
        echo "Waiting for MariaDB..."
        sleep 2
      done

  - name: Install dependencies
    run: composer install --prefer-dist --no-progress --no-interaction

  - name: Prepare Symfony .env
    run: cp .env.test .env

  - name: Setup DB and run migrations
    run: |
      php bin/console doctrine:database:create --env=test
      php bin/console doctrine:migrations:migrate --no-interaction --env=test

  - name: Run PHPUnit tests
    run: php vendor/bin/phpunit
